name: Ultimate Application
description: Application which can autoload the configuration and performs all the necessary stuffs
author: Devashish Mali
port: 8080
environment: prod
modules:
  admin:
    active: true
    name: Admin
  auth:
    active: false
    name: Auth
  email:
    active: false
    name: Email
