name: Ultimate Application
description: Application which can autoload the configuration and performs all the necessary stuffs.
author: Devashish Mali
port: 8080
environment: dev
modules:
  admin:
    active: true
    name: Admin
  auth:
    active: true
    name: Auth
  email:
    active: true
    name: Email
